### PR TITLE
Branch jack

### PR DESCRIPTION
**Pull request by JDiggs1990**
Last commit message: Finally have data being drawn from file, selecting a field, and setValue-ing as said data. 
Current tests for basic validTest run properly, will be extending to multiple field inputs now... Suspect this isn't the greatest pull request message, but tis what it is.

### CODE REVIEW

**Review by Wom2 — APPROVED** [review]
Seems fine, why is it having conflicts?

**Comment by Wom2** [comment]
You could probably completely remove the testData folder since I got a more complete version.

**Review by Wom2 — APPROVED** [review]
U good bro

**Review by Wom2 — COMMENTED** [review]
NOOOOOOOOOOOO!

**Comment by JDiggs1990** [comment]
Because nothing is presently working, more specifically, namefirst and testdata files were deleted to try to resolve conflicts but that failed.

**Pull request closed without merging**
